version: "3"

services:
  app:
    build: .
    command: sh -c "uvicorn main:app --port=8000 --host 0.0.0.0"
    environment:
      - BUILD_MODE=production
    env_file:
      - .env.production
    ports:
      - 8000:8000
    volumes:
      - .:/app